version: "3.9"
services:

  db:
    image: fug0/event_reminder:db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  event_reminder:
    image: fug0/event_reminder:bot
    container_name: bot
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mysql://db:3306/event_reminder
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "asd123"