- name: Check availability of k8s host
  hosts: localhost
  connection: local
  tasks:
    - name: Wait for k8s port 22
      wait_for:
        host: "192.168.199.216"
        port: 22

- name: Deploy database
  hosts: localhost
  tasks:
    - name: Apply database deployment
      kubernetes.core.k8s:
        apply: true
        namespace: "belyaev-er"
        template: ./templates/db-deployment.yaml

    - name: Apply database service
      kubernetes.core.k8s:
        apply: true
        namespace: "belyaev-er"
        template: ./templates/db-service.yaml
  
- name: Fill db from backup
  hosts: localhost
  tasks:
    - name: Render backup script template
      ansible.builtin.template:
        src: ./templates/db_create.sql
        dest: ./db_create.sql
    - name: Execute backup script
      community.mysql.mysql_db:
        login_host: "192.168.199.216"
        login_port: 30100
        login_user: root
        login_password: root
        name: event-rem-bd
        target: ./db_create.sql
        state: import

- name: Deploy services
  hosts: localhost
  tasks:
    - name: Apply event_reminder deployment
      kubernetes.core.k8s:
        apply: true
        namespace: "belyaev-er"
        template: ./templates/event-reminder-deployment.yaml

    - name: Apply event_reminder service
      kubernetes.core.k8s:
        apply: true
        namespace: "belyaev-er"
        template: ./templates/event_reminder-service.yaml