- name: run local terraform
  hosts: localhost
  tasks:
    - name: Run terraform
      terraform:
        project_path: "./tf"
        force_init: yes
        state: present
      register: trfrm

    - name: Add tg host
      add_host:
        name: event_reminder_server
        groups: nodes
        ansible_host: "{{ trfrm.outputs.servers.value.event_reminder_server}}"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    - name: Add db host
      add_host:
        name: event_reminder_db_server
        groups: nodes
        ansible_host: "{{ trfrm.outputs.servers.value.event_reminder_db_server}}"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Wait timeout for creating instances
  hosts: localhost
  connection: local

  tasks:
    - name: Wait for db port 22
      wait_for:
        host: "{{ trfrm.outputs.servers.value.event_reminder_server}}"
        port: 22

    - name: Wait for tg port 22
      wait_for:
        host: "{{ trfrm.outputs.servers.value.event_reminder_db_server}}"
        port: 22

- hosts: event_reminder_db_server
  name: Start mysql server
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server-8.0
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL using pip
      pip:
        name: pymysql
        state: present
        executable: pip3

    - name: Change server configuration
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^bind-address"
        line: "bind-address = 0.0.0.0"

    - name: Start MySQL service
      service:
        name: mysql
        state: restarted
        enabled: yes

    - name: Install net-tools
      apt:
        name: net-tools
        state: present

    - name: Add user
      mysql_user:
        name: "user"
        password: "asd123"
        priv: "event_reminder.*:ALL"
        host: "%"  # Разрешить подключение с любого хоста
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Copy sql import script
      copy:
        src: "{{ sql_path  }}"
        dest: /home/ubuntu

    - name: Import database dump
      mysql_db:
        name: event_reminder
        state: import
        login_unix_socket: /var/run/mysqld/mysqld.sock
        target: /home/ubuntu/db_create.sql


- hosts: event_reminder_server
  name: Deploy application
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install JDK 18
      apt:
        name: openjdk-18-jdk
        state: present

    - name: Copy jar archive
      copy:
        src: "{{ jar_path }}"
        dest: /home/ubuntu/

    - name: Set application as service
      copy:
        src: "{{ unit_path }}"
        dest: /etc/systemd/system/
        
    - name: Deploy Java application
      systemd:
        daemon_reload: true
        state: restarted
        name: event_reminder