parameter_defaults:
  key_name: belyaev
  image_id: ubuntu-22.04
  flavor: m1.small
  st_network_name: 17eae9b6-2168-4a07-a0d3-66d5ad2a9f0e
  floating_network_name: 6b53e929-07cc-4342-a0f4-61a6c9908c04
