apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: db
  name: db
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31308
  selector:
    io.kompose.service: db